# Generated by Django 2.2.16 on 2021-12-21 21:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authtoken', '0004_auto_20211222_0013'),
        ('foodgram_app', '0002_auto_20211222_0013'),
        ('admin', '0004_auto_20211222_0013'),
        ('users', '0002_auto_20211221_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
