# Generated by Django 2.2.16 on 2021-12-21 21:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authtoken', '0004_auto_20211222_0013'),
        ('admin', '0004_auto_20211222_0013'),
        ('auth', '0011_update_proxy_permissions'),
        ('foodgram_app', '0002_auto_20211222_0013'),
        ('users', '0003_auto_20211222_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
