# Generated by Django 2.2.16 on 2021-12-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0002_auto_20211222_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('measurement_unit', models.CharField(max_length=100)),
            ],
        ),
    ]
