# Generated by Django 2.2.16 on 2022-01-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=439124, max_length=150, unique=True, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=100, verbose_name='measurement_unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=256, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(choices=[('1', 'Breakfast'), ('2', 'Dinner'), ('3', 'Lunch')], max_length=256, verbose_name='Tags'),
        ),
    ]
