# Generated by Django 2.2.16 on 2022-01-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0005_auto_20220103_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=150, unique=True, verbose_name='Color'),
        ),
    ]
