# Generated by Django 2.2.16 on 2022-01-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0014_auto_20220110_1213'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase_list',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'recipe'), name='unique_purchase_list'),
        ),
    ]
