# Generated by Django 2.2.16 on 2022-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0015_auto_20220111_0123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase_list',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_purchase_list'),
        ),
    ]
